### ISSUE TITLE
Some packages are named phoremarketplace, others are named OpenBazaar.

### ISSUE THREAD

**Issue by tohsnoom** [phoreproject/openbazaar-desktop#17]
Brief Description: 

Operating System (OS and version): 
Phore Marketplace version (shown on `About Phore Marketplace` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by meyer9** [comment]
Fixed
