### ISSUE TITLE
Default name starts with OB

### ISSUE THREAD

**Issue by tohsnoom** [phoreproject/openbazaar-desktop#18]
Brief Description: 

Operating System (OS and version): OSX High Sierra
Phore Marketplace version (shown on `About Phore Marketplace` page in menu): v1.2.2
Hardware: MacBook Pro

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:
During initial setup, default name starts with the letters OB.

Expected Behavior:
Suggest starting default names with PM.

Additional info (links, images, etc go here):

**Comment by meyer9** [comment]
This is fixed.
