### ISSUE TITLE
Marketplace wallet "need bitcoin"

### ISSUE THREAD

**Issue by Keyser123** [phoreproject/openbazaar-desktop#22]
Brief Description: 

Operating System (OS and version): mac high sierra
Phore Marketplace version (shown on `About Phore Marketplace` page in menu): 1.2.2

The "receive" funds tab in the wallet shows "need bitcoin?" when it should show "need phore?".  the link is correct as it takes you to the phore.io page with the listed exchanges where you can buy phore.
<img width="521" alt="screen shot 2018-03-20 at 11 11 27 pm" src="https://user-images.githubusercontent.com/37606513/37693337-5db6223c-2c95-11e8-9e66-9c4a611051a1.png">

**Comment by meyer9** [comment]
fixed
