### ISSUE TITLE
Pay popup confirmation is empty

### ISSUE THREAD

**Issue by listonjesse** [phoreproject/openbazaar-desktop#32]
Brief Description: Click on pay for an item and observe an empty confirmation. See image.

Operating System (OS and version): Windows 10 RS4

Phore Marketplace version (shown on `About Phore Marketplace` page in menu): 
1.3.2

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Additional info (links, images, etc go here):
![capture4](https://user-images.githubusercontent.com/7820952/37882083-cff5531e-3054-11e8-8db0-966f7c922ea7.PNG)

**Comment by liray-unendlich** [comment]
This is not empty. White text is in the popup.
Same as #28 .
