### ISSUE TITLE
Suggestions & Toggling the Ratings leads to no results

### ISSUE THREAD

**Issue by icculus479** [phoreproject/openbazaar-desktop#33]
Brief Description:  If using Suggestions, any toggling of the ratings buttons will not allow the user to ever clear the search and get back to the main page.  Only a refreshing of the phore marketplace will wipe the 'slate' clean.  See steps below

Operating System (OS and version): Windows 10
Phore Marketplace version (shown on `About Phore Marketplace` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Use any 'Suggestion', click on it
2. Change the Rating to 1 Star & Up
3. Change the Rating back to 5 stars
4.  Remove the suggestion name in the search box, click search
5.  No matter what you do at this point, unless you reload via the Discover button in the toolbar, will always return "No listings match your search criteria"

Observed Behavior:
"No listings match your search criteria"

Expected Behavior:
After clearing out any words in the Phore search box and clicking search, it should default to the main Phore Marketplace screen.

If you don't not toggle the ratings, you can remove the search word, click the search button, and see the default page.  The toggling of the ratings is screwing it up.

Additional info (links, images, etc go here):

**Comment by meyer9** [comment]
Duplicate #34
