### ISSUE TITLE
Ratings filtering issue

### ISSUE THREAD

**Issue by icculus479** [phoreproject/openbazaar-desktop#34]
Brief Description: On the main Phore search page, the rating is set to 5 stars.  If you change the rating to 1 Star, everything remains to be displayed.  However selecting any other rating at this point leads to no results.  This could be an issue due to the fact there are no ratings yet?

Operating System (OS and version): Windows 10
Phore Marketplace version (shown on `About Phore Marketplace` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Enter the Phore Marketplace
2. Click the radio button "One start & Up"
3. Click any other radio button
4. All listings are removed "No listings match your search criteria"

Observed Behavior:
Selecting any Rating other than One Star & Up removes all the listings.

Expected Behavior:
If the page loaded at 5 stars, clicking back to it should display all items.

Additional info (links, images, etc go here):  This could be related to issue #33 where perhaps since there are NO ratings at this time, the default filters aren't working well.

**Comment by meyer9** [comment]
Right, if there aren't any ratings, the items default to 1 star. This is expected behavior.
